apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-student4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-student4
  template:
    metadata:
      labels:
        app: gitops-demo-student4
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: gitops-demo-student4-config
